name: aarch64_generic-openwrt-23.05

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载工具链
        shell: bash
        run: | 
          sudo timedatectl set-timezone Asia/Shanghai
          #下载编译工具链
          wget -q -c https://downloads.openwrt.org/releases/23.05.0/targets/rockchip/armv8/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz -P /opt/gcc/
          tar -xJf /opt/gcc/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C /opt/gcc/
          git clone https://github.com/lmq8267/luci-app-vnt.git /opt/vnt
          cp -R /opt/vnt/luci-app-vnt /opt/gcc/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64/package/luci-app-vnt
      - name: 编译
        shell: bash
        run: |
          cd /opt/gcc/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64
          ./scripts/feeds update -a
          make defconfig
          make package/luci-app-vnt/compile V=s -j1
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: aarch64_generic-openwrt-23.05
         path: /opt/gcc/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64/bin/packages/aarch64_generic/base/*
