name: 编译luci-app-vnt

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写发布的版本'
        required: false
        default: ''
      text:
        description: '请填写发布的说明'
        required: false
        default: ''
env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai
permissions:
  contents: write
jobs:
 build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - APP : APK
            TARGET: aarch64_generic
            SDK : /opt/sdk.tar.zst
            URL: https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/openwrt-sdk-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst

          - APP : IPK
            TARGET: aarch64_generic
            SDK : /opt/sdk.tar.xz
            URL: https://downloads.openwrt.org/releases/22.03.5/targets/rockchip/armv8/openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装SDK
        run: |
          wget -qO ${{ matrix.SDK }} ${{ matrix.URL }}
          if [ "${{ matrix.APP }}" = "APK" ]; then
              tar -I zstd -xf ${{ matrix.SDK }} -C /opt
          else
              tar -xJf ${{ matrix.SDK }} -C /opt
          fi
          cp -R ${{ github.workspace }}/luci-app-vnt /opt/luci-app-vnt
          cd /opt/openwrt-sdk*/package
          cp -R /opt/luci-app-vnt .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
      - name: 开始编译
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          cd /opt/openwrt-sdk*
          make package/luci-app-vnt/compile V=s -j1
          cd /opt/openwrt-sdk*/bin/packages/${{ matrix.TARGET }}/base
          if [ "${{ matrix.APP }}" = "APK" ]; then
              mv luci-app-vnt*.apk luci-app-vnt_all.apk
              echo "APK跳过签名验证安装命令： apk add --allow-untrusted luci-app-vnt_all.apk"
          else
              mv luci-app-vnt*.ipk luci-app-vnt_all.ipk
          fi
          mkdir -p /opt/out
          cp -rf luci-app-vnt* /opt/out/
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-vnt_${{ matrix.APP }}
          path: /opt/outapk/
      
      - name: 发布
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            body: |
             > ### 编译时间 ：${{ env.build_time }}

             - 需要先去系统自带的软件包里已经安装 _**luci**_ 和 _**luci-base**_ 和 _**luci-compat**_ 和 _**kmod-tun**_ 再安装这个ipk才能显示界面

             - 安装完成后找不到界面入口的，请注销登录关闭当前浏览器窗口重新打开或重启路由器
             
             - 如果 状态-系统日志里 出现下图日志内容可以使用以下命令解决
             ![image](https://github.com/lmq8267/luci-app-vnt/assets/119713693/5094717e-a301-4411-9450-c8b64d4a3ade)
             `sed -i 's/util/xml/g' /usr/lib/lua/luci/model/cbi/vnt.lua`

             - **`luci-app-vnt-*.apk` 是OpenWrt新版的APK包** 对于apk包跳过证书命令
             `apk add --allow-untrusted luci-app-vnt.apk`

             ${{ github.event.inputs.text }}
           
            tag_name: ${{ env.TAG }}
            files: /opt/out/*
